yolo_model:

  config_file:
    name: yolov3-tiny-obj_6000.cfg
  weight_file:
    name: yolov3-tiny-obj_5000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - ball
      - person
      - rect
